name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: math-check
        run: |
          cd ..
          cd ..
          python -m unittest test_math_func.py
