name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: Checkout
        run: actions/checkout@v4
      - name: math-check
        run: |
          python -m unittest test_math_func.py
